-- ******************************** SqlDBM: Snowflake *******************************
-- * Generated by SqlDBM: AdWorks project, v246 by lesya.rylova+fromSerge@gmail.com *


CREATE OR REPLACE SCHEMA "AdventureworksdwEdw";

CREATE OR REPLACE SCHEMA "AdventureworksdwInformationSchema"
COMMENT = 'Views describing the contents of schemas in this database';

CREATE OR REPLACE SCHEMA "EDW";

CREATE OR REPLACE SCHEMA "Edw1";

CREATE OR REPLACE SCHEMA "HOTELBNB";

-- ************************************** "EDW"."Seq_Demo123"
CREATE SEQUENCE IF NOT EXISTS "EDW"."Seq_Demo123"
START WITH 1
INCREMENT BY 1;

-- ************************************** "Test"
CREATE OR REPLACE TABLE "Test"
(
 "EtlId"       date NOT NULL COMMENT 'hello', -- From template: "table_w_etl_fields" 
 "EtlFilename" varchar(50) NOT NULL COMMENT 'source file or table from where the target is loaded' -- From template: "table_w_etl_fields"
);

-- ************************************** "Table954"
CREATE OR REPLACE TABLE "Table954"
(
 "EtlId"       date NOT NULL,
 "EtlFilename" varchar NOT NULL COMMENT 'source file or table from where the target is loaded'
);

-- ************************************** "Table719"
CREATE OR REPLACE TABLE "Table719"
(
 "NewTablePk"  varchar NOT NULL,
 "EtlId"       date NOT NULL COMMENT 'hello', -- From template: "table_w_etl_fields" 
 "EtlFilename" varchar(50) NOT NULL COMMENT 'source file or table from where the target is loaded', -- From template: "table_w_etl_fields" 
 CONSTRAINT "PK_Table719_NewTablePk_Pk730" PRIMARY KEY ( "NewTablePk" )
);

-- ************************************** "Table548"
CREATE OR REPLACE TABLE "Table548"
(
 "NewPk" varchar NOT NULL,
 CONSTRAINT "PK_Table548_NewPk_Pk551" PRIMARY KEY ( "NewPk" )
);

-- ************************************** "Table544Copy11"
CREATE OR REPLACE TABLE "Table544Copy11"
(
 "UnitPrice1"            number(38,0) NOT NULL,
 "ExtendedAmount1"       number(38,0) NOT NULL,
 "UnitPriceDiscountPct1" float,
 "SalesOrderNumber"      varchar(20) NOT NULL,
 "NewCol123"             date NOT NULL
);

-- ************************************** "Table1900"
CREATE OR REPLACE TABLE "Table1900"
(
 "new_col"      NOT NULL,
 "EtlId"       date NOT NULL COMMENT 'hello', -- From template: "table_w_etl_fields" 
 "EtlFilename" varchar(50) NOT NULL COMMENT 'source file or table from where the target is loaded', -- From template: "table_w_etl_fields" 
 CONSTRAINT "PK_Table1900_new_col_1904" PRIMARY KEY ( "new_col" )
);

-- ************************************** "Table1858"
CREATE OR REPLACE TABLE "Table1858"
(
 "EtlId"          date NOT NULL COMMENT 'hello', -- From template: "table_w_etl_fields" 
 "EtlFilename"    varchar(50) NOT NULL COMMENT 'source file or table from where the target is loaded', -- From template: "table_w_etl_fields" 
 "SocialSecurity" number(9,0) NOT NULL, -- From template: "SensitiveCustomerFields" 
 "Address"        varchar -- From template: "SensitiveCustomerFields"
);

-- ************************************** "Table1850"
CREATE OR REPLACE TABLE "Table1850"
(
 "columnB"     integer NOT NULL,
 "columnA"     integer NOT NULL,
 "EtlId"       date NOT NULL COMMENT 'hello', -- From template: "table_w_etl_fields" 
 "EtlFilename" varchar(50) NOT NULL COMMENT 'source file or table from where the target is loaded', -- From template: "table_w_etl_fields" 
 CONSTRAINT "PK_Table1850__1856" PRIMARY KEY ( "columnB" )
);

-- ************************************** "Table1825"
CREATE OR REPLACE TABLE "Table1825"
(
 "EtlId"       date NOT NULL COMMENT 'hello', -- From template: "table_w_etl_fields" 
 "EtlFilename" varchar(50) NOT NULL COMMENT 'source file or table from where the target is loaded' -- From template: "table_w_etl_fields"
);

-- ************************************** "Table1820"
CREATE OR REPLACE TABLE "Table1820"
(
 "EtlId"       date NOT NULL COMMENT 'hello', -- From template: "table_w_etl_fields" 
 "EtlFilename" varchar(50) NOT NULL COMMENT 'source file or table from where the target is loaded' -- From template: "table_w_etl_fields"
);

-- ************************************** "Table1794"
CREATE OR REPLACE TABLE "Table1794"
(
 "EtlId"       date NOT NULL COMMENT 'hello', -- From template: "table_w_etl_fields" 
 "EtlFilename" varchar(50) NOT NULL COMMENT 'source file or table from where the target is loaded' -- From template: "table_w_etl_fields"
);

-- ************************************** "Table1791"
CREATE OR REPLACE TABLE "Table1791"
(
 "EtlId"       date NOT NULL COMMENT 'hello', -- From template: "table_w_etl_fields" 
 "EtlFilename" varchar(50) NOT NULL COMMENT 'source file or table from where the target is loaded' -- From template: "table_w_etl_fields"
);

-- ************************************** "Table1765"
CREATE OR REPLACE TABLE "Table1765"
(
 "EtlId"       date NOT NULL,
 "EtlFilename" varchar(50) NOT NULL COMMENT 'source file or table from where the target is loaded'
);

-- ************************************** "Table1722"
CREATE OR REPLACE TABLE "Table1722"
(
 "EtlId"       date NOT NULL COMMENT 'hello',
 "EtlFilename" varchar(50) NOT NULL COMMENT 'source file or table from where the target is loaded',
 "Lowercase"   integer NOT NULL
);

-- ************************************** "Table1716"
CREATE OR REPLACE TABLE "Table1716"
(
 "EtlId"       date NOT NULL COMMENT 'hello', -- From template: "table_w_etl_fields" 
 "EtlFilename" varchar(50) NOT NULL COMMENT 'source file or table from where the target is loaded' -- From template: "table_w_etl_fields"
);

-- ************************************** "Table1705"
CREATE OR REPLACE TABLE "Table1705"
(
 "EtlId"       date NOT NULL,
 "EtlFilename" varchar(50) NOT NULL COMMENT 'source file or table from where the target is loaded',
 "Lowercase"   varchar(50) NOT NULL
);

-- ************************************** "Table1699"
CREATE OR REPLACE TABLE "Table1699"
(
 "EtlId"          date NOT NULL COMMENT 'hello',
 "EtlFilename"    varchar(50) NOT NULL COMMENT 'source file or table from where the target is loaded',
 "SocialSecurity" number(9,0) NOT NULL, -- From template: "SensitiveCustomerFields" 
 "Address"        varchar -- From template: "SensitiveCustomerFields"
);
-- ************************************** PostScript

grant access

-- ************************************** PostScript End "Table1699"

-- ************************************** "Table1678"
CREATE OR REPLACE TABLE "Table1678"
(
 "NewPk"       integer NOT NULL,
 "EtlId"       date NOT NULL COMMENT 'hello', -- From template: "table_w_etl_fields" 
 "EtlFilename" varchar(50) NOT NULL COMMENT 'source file or table from where the target is loaded', -- From template: "table_w_etl_fields" 
 CONSTRAINT "PK_Table1678_NewPk_Table1678New" PRIMARY KEY ( "NewPk" )
);

-- ************************************** "Table1660"
CREATE OR REPLACE TABLE "Table1660"
(
 "EtlId"          date NOT NULL COMMENT 'hello', -- From template: "table_w_etl_fields" 
 "EtlFilename"    varchar(50) NOT NULL COMMENT 'source file or table from where the target is loaded', -- From template: "table_w_etl_fields" 
 "SocialSecurity" number(9,0) NOT NULL,
 "Address"        varchar
);

-- ************************************** "Table1654"
CREATE OR REPLACE TABLE "Table1654"
(
 "EtlId"       date NOT NULL COMMENT 'hello', -- From template: "table_w_etl_fields" 
 "EtlFilename" varchar(50) NOT NULL COMMENT 'source file or table from where the target is loaded' -- From template: "table_w_etl_fields"
);

-- ************************************** "Edw1"."NewTblCopy1"
CREATE OR REPLACE TABLE "Edw1"."NewTblCopy1"
(
 "EtlId"       date NOT NULL COMMENT 'hello', -- From template: "table_w_etl_fields" 
 "EtlFilename" varchar(50) NOT NULL COMMENT 'source file or table from where the target is loaded' -- From template: "table_w_etl_fields"
);

-- ************************************** "Edw1"."NewTbl"
CREATE OR REPLACE TABLE "Edw1"."NewTbl"
(
 "EtlId"       date NOT NULL COMMENT 'hello', -- From template: "table_w_etl_fields" 
 "EtlFilename" varchar(50) NOT NULL COMMENT 'source file or table from where the target is loaded', -- From template: "table_w_etl_fields" 
 "NewCol"      integer NOT NULL
);

-- ************************************** "NewDimEmp"
CREATE OR REPLACE TABLE "NewDimEmp"
(

);

-- ************************************** "HOTELBNB"."Hotels"
CREATE OR REPLACE TABLE "HOTELBNB"."Hotels"
(
 "CityCode" varchar(3),
 "HotelId"  number(38,0)
);

-- ************************************** "FutureTable"
CREATE OR REPLACE TABLE "FutureTable"
(
 "Pk"          integer NOT NULL,
 "EtlId"       date NOT NULL COMMENT 'hello', -- From template: "table_w_etl_fields" 
 "EtlFilename" varchar(50) NOT NULL COMMENT 'source file or table from where the target is loaded', -- From template: "table_w_etl_fields" 
 CONSTRAINT "PK_FutureTable_Pk_1819" PRIMARY KEY ( "Pk" )
);

-- ************************************** "FctClientSales"
CREATE OR REPLACE TABLE "FctClientSales"
(
 "CliSalesSkey" varchar(50) NOT NULL,
 "EtlId"        date NOT NULL COMMENT 'hello', -- From template: "table_w_etl_fields" 
 "EtlFilename"  varchar(50) NOT NULL COMMENT 'source file or table from where the target is loaded', -- From template: "table_w_etl_fields" 
 "SalesAmount"  float NOT NULL,
 "ClientId"     integer NOT NULL,
 CONSTRAINT "PK_FctClientSales_CliSalesSkey_1759" PRIMARY KEY ( "CliSalesSkey" )
);

-- ************************************** "EDW"."FactInternetSalesCopy11"
CREATE OR REPLACE TABLE "EDW"."FactInternetSalesCopy11"
(
 "NewCol"                integer NOT NULL,
 "ProductKey"            number(38,0) NOT NULL,
 "OrderDateKey"          number(38,0) NOT NULL,
 "DueDateKey"            number(38,0) NOT NULL,
 "ShipDateKey"           number(38,0) NOT NULL,
 "CustomerKey"           number(38,0) NOT NULL,
 "PromotionKey"          number(38,0) NOT NULL,
 "CurrencyKey"           number(38,0) NOT NULL,
 "SalesTerritoryKey"     number(38,0) NOT NULL,
 "SalesOrderNumber"      varchar(20) NOT NULL,
 "SalesOrderLineNumber"  number(38,0) NOT NULL,
 "RevisionNumber"        number(38,0) NOT NULL,
 "OrderQuantity"         number(38,0) NOT NULL,
 "UnitPrice"             number(38,0) NOT NULL,
 "ExtendedAmount"        number(38,0) NOT NULL,
 "UnitPriceDiscountPct"  float,
 "DiscountAmount"        float NOT NULL,
 "ProductStandardCost"   number(38,0) NOT NULL,
 "TotalProductCost"      number(38,0) NOT NULL,
 "SalesAmount"           number(38,0) NOT NULL,
 "TaxAmt"                number(38,0) NOT NULL,
 "Freight"               number(38,0) NOT NULL,
 "CarrierTrackingNumber" varchar(25),
 "CustomerPoNumber"      varchar(25),
 "NewPk"                 varchar NOT NULL,
 CONSTRAINT "PK_FactInternetSalesCopy11_NewCol_1448" PRIMARY KEY ( "NewCol" )
)
COMMENT = 'Fact table to hold Currency Data';

-- ************************************** "EDW"."FactInternetSalesCopy1"
CREATE OR REPLACE TABLE "EDW"."FactInternetSalesCopy1"
(
 "NewCol"                integer NOT NULL,
 "ProductKey"            number(38,0) NOT NULL,
 "OrderDateKey"          number(38,0) NOT NULL,
 "DueDateKey"            number(38,0) NOT NULL,
 "ShipDateKey"           number(38,0) NOT NULL,
 "CustomerKey"           number(38,0) NOT NULL,
 "PromotionKey"          number(38,0) NOT NULL,
 "CurrencyKey"           number(38,0) NOT NULL,
 "SalesTerritoryKey"     number(38,0) NOT NULL,
 "SalesOrderNumber"      varchar(20) NOT NULL,
 "SalesOrderLineNumber"  number(38,0) NOT NULL,
 "RevisionNumber"        number(38,0) NOT NULL,
 "OrderQuantity"         number(38,0) NOT NULL,
 "UnitPrice"             number(38,0) NOT NULL,
 "ExtendedAmount"        number(38,0) NOT NULL,
 "UnitPriceDiscountPct"  float,
 "DiscountAmount"        float NOT NULL,
 "ProductStandardCost"   number(38,0) NOT NULL,
 "TotalProductCost"      number(38,0) NOT NULL,
 "SalesAmount"           number(38,0) NOT NULL,
 "TaxAmt"                number(38,0) NOT NULL,
 "Freight"               number(38,0) NOT NULL,
 "CarrierTrackingNumber" varchar(25),
 "CustomerPoNumber"      varchar(25),
 "NewPk"                 varchar NOT NULL,
 CONSTRAINT "PK_FactInternetSalesCopy1_NewCol_Pk543" PRIMARY KEY ( "NewCol" )
)
CLUSTER BY ( "ProductKey" )
COMMENT = 'Fact table to hold Currency Data';

-- ************************************** "DimStoreCopy1"
CREATE OR REPLACE TABLE "DimStoreCopy1"
(
 "StoreId"      integer NOT NULL DEFAULT "EDW"."Seq_Demo123".nextval,
 "Address"      string NOT NULL,
 "SizeCategory" varchar(1) NOT NULL,
 "ParentPk"     varchar(50) NOT NULL,
 CONSTRAINT "PK_DimStoreCopy1_StoreId_PkDimStoreStoreIdPk853" PRIMARY KEY ( "StoreId" )
)
COMMENT = 'Store and PoS location';

-- ************************************** "DimStore"
CREATE OR REPLACE TABLE "DimStore"
(
 "StoreId"      integer NOT NULL DEFAULT "EDW"."Seq_Demo123".nextval,
 "Address"      string NOT NULL,
 "SizeCategory" varchar(1) NOT NULL,
 "ParentPk"     varchar(50) NOT NULL,
 "NewCol"       varchar(50) NOT NULL,
 "C"            int NOT NULL,
 CONSTRAINT "PK_DimStore_StoreId_Pk853" PRIMARY KEY ( "StoreId" )
)
COMMENT = 'Store and PoS location';

-- ************************************** "EDW"."DimScenario"
CREATE OR REPLACE TABLE "EDW"."DimScenario"
(
 "ScenarioKey"  number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'Scenario Identifier',
 "ScenarioName" varchar(50) COMMENT 'Name of the Scenario',
 "CreatedBy"    varchar(50) NOT NULL COMMENT 'Who Created this Scenario',
 "CreatedDate"  timestamp_ntz(9) NOT NULL COMMENT 'Scenario Creation Date',
 "UpdatedDate"  timestamp_ntz(9) NOT NULL,
 "UpdatedBy"    varchar(50) NOT NULL,
 "TestCol"      varchar(50) NOT NULL,
 CONSTRAINT "PK_DimScenario_ScenarioKey_PkDimScenario" PRIMARY KEY ( "ScenarioKey" )
)
COMMENT = 'Dimension Scenario';

-- ************************************** "EDW"."DimSalesTerritory"
CREATE OR REPLACE TABLE "EDW"."DimSalesTerritory"
(
 "SalesTerritoryKey"          number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 "SalesTerritoryGroup"        varchar(50) NOT NULL,
 "SalesTerritoryAlternateKey" number(38,0),
 "SalesTerritoryRegion"       varchar(50) NOT NULL,
 "SalesTerritoryCountry"      varchar(50) NOT NULL,
 CONSTRAINT "PK_DimSalesTerritory_SalesTerritoryGroup_SalesTerritoryKey_PkDimSalesTerritory" PRIMARY KEY ( "SalesTerritoryKey", "SalesTerritoryGroup" )
)
COMMENT = 'Sales Territory data';

-- ************************************** "EDW"."DimPromotion"
CREATE OR REPLACE TABLE "EDW"."DimPromotion"
(
 "PromotionKey"             number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 "PromotionAlternateKey"    number(38,0),
 "EnglishPromotionName"     varchar(255),
 "SpanishPromotionName"     varchar(255),
 "FrenchPromotionName"      varchar(255),
 "DiscountPct"              float,
 "EnglishPromotionType"     varchar(50),
 "SpanishPromotionType"     varchar(50),
 "FrenchPromotionType"      varchar(50),
 "EnglishPromotionCategory" varchar(50),
 "SpanishPromotionCategory" varchar(50),
 "FrenchPromotionCategory"  varchar(50),
 "MinQty"                   number(38,0),
 "MaxQty"                   number(38,0),
 "NewCol"                   varchar(50) NOT NULL,
 CONSTRAINT "PK_DimPromotion_PromotionKey_PkDimPromotion" PRIMARY KEY ( "PromotionKey" )
);

-- ************************************** "EDW"."DimProductCategory"
CREATE OR REPLACE TABLE "EDW"."DimProductCategory"
(
 "ProductCategoryKey"          number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 "ProductCategoryAlternateKey" number(38,0),
 "EnglishProductCategoryName"  varchar(50) NOT NULL,
 "SpanishProductCategoryName"  varchar(50) NOT NULL,
 "FrenchProductCategoryName"   varchar(50) NOT NULL,
 CONSTRAINT "PK_DimProductCategory_ProductCategoryKey_PkDimProductCategory" PRIMARY KEY ( "ProductCategoryKey" )
);

-- ************************************** "EDW"."DimOrganization"
CREATE OR REPLACE TABLE "EDW"."DimOrganization"
(
 "OrganizationKey"       number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'org key from HR , format xyz_nnnnn',
 "ParentOrganizationKey" number(38,0) COMMENT 'parent org',
 "PercentageOfOwnership" varchar(16),
 "OrganizationName"      varchar(50),
 "CurrencyKey"           number(38,0),
 CONSTRAINT "PK_DimOrganization_OrganizationKey_PkDimOrganization" PRIMARY KEY ( "OrganizationKey" )
)
COMMENT = 'Dimension for Organizational Data';

-- ************************************** "EDW"."DimGeography"
CREATE OR REPLACE TABLE "EDW"."DimGeography"
(
 "GeographyKey"             number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 "City"                     varchar(30),
 "StateProvinceCode"        varchar(3),
 "StateProvinceName"        varchar(50),
 "CountryRegionCode"        varchar(3),
 "EnglishCountryRegionName" varchar(50),
 "SpanishCountryRegionName" varchar(50),
 "FrenchCountryRegionName"  varchar(50),
 "PostalCode"               varchar(15),
 "SalesTerritoryKey"        number(38,0),
 "IpAddressLocator"         varchar(15),
 CONSTRAINT "PK_DimGeography_GeographyKey_PkDimGeography" PRIMARY KEY ( "GeographyKey" )
);

-- ************************************** "DimEmployee"
CREATE OR REPLACE TABLE "DimEmployee"
(
 "EmployeeId"  integer NOT NULL DEFAULT 5,
 "EtlId"       date NOT NULL COMMENT 'hello', -- From template: "table_w_etl_fields" 
 "EtlFilename" varchar(50) NOT NULL COMMENT 'source file or table from where the target is loaded', -- From template: "table_w_etl_fields" 
 CONSTRAINT "PK_DimEmployee_EmployeeId_1600" PRIMARY KEY ( "EmployeeId" )
);

-- ************************************** "EDW"."DimDepartmentGroup"
CREATE OR REPLACE TABLE "EDW"."DimDepartmentGroup"
(
 "DepartmentGroupKey"       number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'Org hierarchy from salesforce',
 "ParentDepartmentGroupKey" number(38,0) NOT NULL,
 "DepartmentGroupName"      varchar(50) NOT NULL,
 CONSTRAINT "PK_DimDepartmentGroup_DepartmentGroupKey_PkDimDepartmentGroup" PRIMARY KEY ( "DepartmentGroupKey" ),
 CONSTRAINT "Ak1745" UNIQUE ( "DepartmentGroupName", "ParentDepartmentGroupKey" )
)
COMMENT = 'Dimension for Department groups';

-- ************************************** "EDW"."DimDate"
CREATE OR REPLACE TABLE "EDW"."DimDate"
(
 "DateKey"              number(38,0) NOT NULL,
 "FullDateAlternateKey" date NOT NULL,
 "DayNumberOfWeek"      number(38,0) NOT NULL,
 "EnglishDayNameOfWeek" varchar(10) NOT NULL,
 "SpanishDayNameOfWeek" varchar(10) NOT NULL,
 "FrenchDayNameOfWeek"  varchar(10) NOT NULL,
 "DayNumberOfMonth"     number(38,0) NOT NULL,
 "DayNumberOfYear"      number(38,0) NOT NULL,
 "WeekNumberOfYear"     number(38,0) NOT NULL,
 "EnglishMonthName"     varchar(10) NOT NULL,
 "SpanishMonthName"     varchar(10) NOT NULL,
 "FrenchMonthName"      varchar(10) NOT NULL,
 "MonthNumberOfYear"    number(38,0) NOT NULL,
 "CalendarQuarter"      number(38,0) NOT NULL,
 "CalendarYear"         number(38,0) NOT NULL,
 "CalendarSemester"     number(38,0) NOT NULL,
 "FiscalQuarter"        number(38,0) NOT NULL,
 "FiscalYear"           number(38,0) NOT NULL,
 "FiscalSemester"       number(38,0) NOT NULL,
 CONSTRAINT "PK_DimDate_DateKey_PkDimDate" PRIMARY KEY ( "DateKey" )
)
COMMENT = 'Dimension for Date time';

-- ************************************** "EDW"."DimcUrrency"
CREATE OR REPLACE TABLE "EDW"."DimcUrrency"
(
 "CurrencyKey"          number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'Currency Identifier',
 "CurrencyAlternateKey" varchar(3) NOT NULL COMMENT 'Alternate Currency Identifier',
 "CurrencyName"         varchar(50) NOT NULL COMMENT 'Name of the Currency',
 CONSTRAINT "PK_DimcUrrency_CurrencyKey_PkDimCurrency" PRIMARY KEY ( "CurrencyKey" )
)
COMMENT = 'Dimension for Currency Data';

-- ************************************** "DimClientHist"
CREATE OR REPLACE TABLE "DimClientHist"
(
 "ClientId"    integer NOT NULL,
 "ValidFrom"   date NOT NULL,
 "ValidTo"     date NOT NULL,
 "EtlId"       date NOT NULL COMMENT 'hello', -- From template: "table_w_etl_fields" 
 "EtlFilename" varchar(50) NOT NULL COMMENT 'source file or table from where the target is loaded', -- From template: "table_w_etl_fields" 
 "ClientName"  varchar NOT NULL,
 "NewCol"      integer NOT NULL,
 CONSTRAINT "PK_DimClientHist_ClientId_ValidFrom_ValidTo_1807" PRIMARY KEY ( "ClientId", "ValidFrom", "ValidTo" ),
 CONSTRAINT "AkSingleCli" UNIQUE ( "ClientId" )
);

-- ************************************** "EDW"."DimAccount"
CREATE OR REPLACE TABLE "EDW"."DimAccount"
(
 "AccountKey"                    number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'Unique Identifier of the Account data',
 "ParentAccountKey"              number(38,0) COMMENT 'Identifier of parent Account',
 "AccountCodeAlternateKey"       number(38,0) COMMENT 'some info on alternate key',
 "ParentAccountCodeAlternateKey" number(38,0) COMMENT 'Client team maintains this, see Bob',
 "AccountDescription"            varchar(50),
 "AccountType"                   varchar(50) COMMENT 'Checking or savings',
 "Operator"                      varchar(50) COMMENT 'Bank or online assistant',
 "CustomMembers"                 varchar(300),
 "ValueType"                     varchar(50),
 "CustomMemberOptions"           varchar(200),
 "new_cool"                      int NOT NULL,
 CONSTRAINT "PK_DimAccount_AccountKey_PkDimAccount" PRIMARY KEY ( "AccountKey" )
)
COMMENT = 'Holds all Account information';

-- ************************************** "HOTELBNB"."DESTINATIONS"
CREATE OR REPLACE TABLE "HOTELBNB"."DESTINATIONS"
(
 "DESTINATION_ID"               varchar(3) NOT NULL,
 "DESTINATION_NAME"             varchar(1000),
 "CITY_CODE"                    varchar(3),
 "COUNTRY_CODE"                 varchar(3),
 "COUNTRY_NAME"                 varchar(1000),
 "COMMERCIAL_FINANCE_REGION"    varchar(1000),
 "COMMERCIAL_FINANCE_SUBREGION" varchar(1000),
 "HOTEL_DEST_REGION"            varchar(1000),
 "HOTEL_DEST_SUBREGION"         varchar(1000),
 "HOTEL_DEST_SUBREGION2"        varchar(1000),
 "BTB_SO_REGION"                varchar(1000),
 "BTB_SO_SUBREGION"             varchar(1000),
 CONSTRAINT "DESTINATIONS_PK" PRIMARY KEY ( "DESTINATION_ID" )
);

-- ************************************** "HOTELBNB"."Bookings"
CREATE OR REPLACE TABLE "HOTELBNB"."Bookings"
(
 "BookingId"    varchar(12),
 "HotelId"      number(38,0),
 "Rn"           number(38,0) COMMENT 'room nights',
 "CreationDate" varchar(10)
);

-- ************************************** "Table544Copy1"
CREATE OR REPLACE TABLE "Table544Copy1"
(
 "NewCol"               integer NOT NULL,
 "SalesOrderNumber"     varchar(20) NOT NULL,
 "UnitPrice"            number(38,0) NOT NULL,
 "ExtendedAmount"       number(38,0) NOT NULL,
 "UnitPriceDiscountPct" float,
 CONSTRAINT "Fk545Copy1" FOREIGN KEY ( "NewCol" ) REFERENCES "EDW"."FactInternetSalesCopy1" ( "NewCol" )
);

-- ************************************** "Table1905"
CREATE OR REPLACE TABLE "Table1905"
(
 "EtlId"       date NOT NULL COMMENT 'hello', -- From template: "table_w_etl_fields" 
 "EtlFilename" varchar(50) NOT NULL COMMENT 'source file or table from where the target is loaded', -- From template: "table_w_etl_fields" 
 "new_col"      NOT NULL,
 CONSTRAINT "Fk1908" FOREIGN KEY ( "new_col" ) REFERENCES "Table1900" ( "new_col" )
);

-- ************************************** "Table1558Copy1"
CREATE OR REPLACE TABLE "Table1558Copy1"
(
 "EtlId"       date NOT NULL COMMENT 'hello', -- From template: "table_w_etl_fields" 
 "EtlFilename" varchar(50) NOT NULL COMMENT 'source file or table from where the target is loaded', -- From template: "table_w_etl_fields" 
 "StoreId"     integer NOT NULL DEFAULT "EDW"."Seq_Demo123".nextval,
 CONSTRAINT "Fk1561Copy1" FOREIGN KEY ( "StoreId" ) REFERENCES "DimStoreCopy1" ( "StoreId" )
);

-- ************************************** "EDW"."NewFactCurrencyRate"
CREATE OR REPLACE TABLE "EDW"."NewFactCurrencyRate"
(
 "AverageRate"  float,
 "CurrencyId"   varchar(3),
 "CurrencyDate" date,
 "EndOfDayRate" float,
 "CurrencyKey"  number(38,0),
 "DateKey"      number(38,0),
 "LowerCol"     integer NOT NULL,
 CONSTRAINT "FkNewFactCurrencyRate469" FOREIGN KEY ( "CurrencyKey" ) REFERENCES "EDW"."DimcUrrency" ( "CurrencyKey" ),
 CONSTRAINT "FkNewFactCurrencyRate471" FOREIGN KEY ( "DateKey" ) REFERENCES "EDW"."DimDate" ( "DateKey" )
);

-- ************************************** "NewChild"
CREATE OR REPLACE TABLE "NewChild"
(
 "EtlId"        date NOT NULL COMMENT 'hello', -- From template: "table_w_etl_fields" 
 "EtlFilename"  varchar(50) NOT NULL COMMENT 'source file or table from where the target is loaded', -- From template: "table_w_etl_fields" 
 "CliSalesSkey" varchar(50) NOT NULL,
 CONSTRAINT "Fk1802" FOREIGN KEY ( "CliSalesSkey" ) REFERENCES "FctClientSales" ( "CliSalesSkey" )
);

-- ************************************** "EDW"."FactSurveyResponse"
CREATE OR REPLACE TABLE "EDW"."FactSurveyResponse"
(
 "SurveyResponseKey"             number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 "DateKey"                       number(38,0) NOT NULL,
 "CustomerKey"                   number(38,0) NOT NULL,
 "ProductCategoryKey"            number(38,0) NOT NULL,
 "EnglishProductCategoryName"    varchar(50) NOT NULL,
 "ProductSubcategoryKey"         number(38,0) NOT NULL,
 "EnglishProductSubcategoryName" varchar(50) NOT NULL,
 CONSTRAINT "FkFactSurveyResponse465" FOREIGN KEY ( "DateKey" ) REFERENCES "EDW"."DimDate" ( "DateKey" ),
 CONSTRAINT "FkFactSurveyResponse467" FOREIGN KEY ( "ProductCategoryKey" ) REFERENCES "EDW"."DimProductCategory" ( "ProductCategoryKey" )
);

-- ************************************** "EDW"."FactSalesQuota"
CREATE OR REPLACE TABLE "EDW"."FactSalesQuota"
(
 "SalesQuotaKey"    number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 "EmployeeKey"      number(38,0) NOT NULL,
 "DateKey"          number(38,0) NOT NULL,
 "CalendarYear"     number(38,0) NOT NULL,
 "CalendarQuarter"  number(38,0) NOT NULL,
 "SalesAmountQuota" number(38,0) NOT NULL,
 CONSTRAINT "FkFactSalesQuota463" FOREIGN KEY ( "DateKey" ) REFERENCES "EDW"."DimDate" ( "DateKey" )
);

-- ************************************** "EDW"."FactProductInventory"
CREATE OR REPLACE TABLE "EDW"."FactProductInventory"
(
 "ProductKey"   number(38,0) NOT NULL,
 "DateKey"      number(38,0) NOT NULL COMMENT 'data hash md5',
 "MovementDate" date NOT NULL,
 "UnitCost"     number(38,0) NOT NULL,
 "UnitsIn"      number(38,0) NOT NULL,
 "UnitsOut"     number(38,0) NOT NULL,
 "UnitsBalance" number(38,0) NOT NULL,
 CONSTRAINT "FkFactProductInventory443" FOREIGN KEY ( "DateKey" ) REFERENCES "EDW"."DimDate" ( "DateKey" )
);

-- ************************************** "EDW"."FactInternetSalesCopy11Copy1"
CREATE OR REPLACE TABLE "EDW"."FactInternetSalesCopy11Copy1"
(
 "ProductKey"            number(38,0) NOT NULL,
 "OrderDateKey"          number(38,0) NOT NULL,
 "DueDateKey"            number(38,0) NOT NULL,
 "ShipDateKey"           number(38,0) NOT NULL,
 "CustomerKey"           number(38,0) NOT NULL,
 "PromotionKey"          number(38,0) NOT NULL,
 "CurrencyKey"           number(38,0) NOT NULL,
 "SalesTerritoryKey"     number(38,0) NOT NULL,
 "SalesOrderNumber"      varchar(20) NOT NULL,
 "SalesOrderLineNumber"  number(38,0) NOT NULL,
 "RevisionNumber"        number(38,0) NOT NULL,
 "OrderQuantity"         number(38,0) NOT NULL,
 "UnitPrice"             number(38,0) NOT NULL,
 "ExtendedAmount"        number(38,0) NOT NULL,
 "UnitPriceDiscountPct"  float,
 "DiscountAmount"        float NOT NULL,
 "ProductStandardCost"   number(38,0) NOT NULL,
 "TotalProductCost"      number(38,0) NOT NULL,
 "SalesAmount"           number(38,0) NOT NULL,
 "TaxAmt"                number(38,0) NOT NULL,
 "Freight"               number(38,0) NOT NULL,
 "CarrierTrackingNumber" varchar(25),
 "CustomerPoNumber"      varchar(25),
 "NewPk"                 varchar NOT NULL,
 "NewTablePk"            varchar NOT NULL,
 "Col1"                  integer NOT NULL,
 "Col2"                  string NOT NULL,
 "NewCol"                integer NOT NULL,
 CONSTRAINT "PK_FactInternetSalesCopy11Copy1_NewCol_Pk543" PRIMARY KEY ( "NewCol" ),
 CONSTRAINT "Fk722" FOREIGN KEY ( "NewTablePk" ) REFERENCES "Table719" ( "NewTablePk" )
)
COMMENT = 'Fact table to hold Currency Data';

-- ************************************** "EDW"."FactFinance"
CREATE OR REPLACE TABLE "EDW"."FactFinance"
(
 "FinanceKey"         number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 "DateKey"            number(38,0) NOT NULL,
 "OrganizationKey"    number(38,0) NOT NULL,
 "DepartmentGroupKey" number(38,0) NOT NULL,
 "ScenarioKey"        number(38,0) NOT NULL,
 "AccountKey"         number(38,0) NOT NULL,
 "Amount"             float NOT NULL,
 CONSTRAINT "FkFactFinance417" FOREIGN KEY ( "DateKey" ) REFERENCES "EDW"."DimDate" ( "DateKey" ),
 CONSTRAINT "FkFactFinance419" FOREIGN KEY ( "OrganizationKey" ) REFERENCES "EDW"."DimOrganization" ( "OrganizationKey" ),
 CONSTRAINT "FkFactFinance421" FOREIGN KEY ( "DepartmentGroupKey" ) REFERENCES "EDW"."DimDepartmentGroup" ( "DepartmentGroupKey" ),
 CONSTRAINT "FkFactFinance423" FOREIGN KEY ( "ScenarioKey" ) REFERENCES "EDW"."DimScenario" ( "ScenarioKey" ),
 CONSTRAINT "FkFactFinance425" FOREIGN KEY ( "AccountKey" ) REFERENCES "EDW"."DimAccount" ( "AccountKey" )
)
COMMENT = 'Facts for Finance';

-- ************************************** "EDW"."FactCurrencyRate"
CREATE OR REPLACE TABLE "EDW"."FactCurrencyRate"
(
 "CurrencyKey"  number(38,0) NOT NULL,
 "DateKey"      number(38,0) NOT NULL,
 "AverageRate"  float NOT NULL,
 "EndOfDayRate" float NOT NULL,
 "NewCol"       integer NOT NULL,
 CONSTRAINT "PK_FactCurrencyRate_CurrencyKey_PkFactCurrencyRate1797" PRIMARY KEY ( "CurrencyKey" ),
 CONSTRAINT "FkFactCurrencyRate413" FOREIGN KEY ( "CurrencyKey" ) REFERENCES "EDW"."DimcUrrency" ( "CurrencyKey" ),
 CONSTRAINT "FkFactCurrencyRate415" FOREIGN KEY ( "DateKey" ) REFERENCES "EDW"."DimDate" ( "DateKey" )
);

-- ************************************** "EDW"."DimReseller"
CREATE OR REPLACE TABLE "EDW"."DimReseller"
(
 "ResellerKey"          number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 "GeographyKey"         number(38,0),
 "ResellerAlternateKey" varchar(15),
 "Phone"                varchar(25),
 "BusinessType"         varchar(20) NOT NULL,
 "ResellerName"         varchar(50) NOT NULL,
 "NumberEmployees"      number(38,0) COMMENT 'total emps in reseller location',
 "OrderFrequency"       varchar(1),
 "OrderMonth"           number(38,0),
 "FirstOrderYear"       number(38,0),
 "LastOrderYear"        number(38,0),
 "ProductLine"          varchar(50),
 "AddressLine1"         varchar(60),
 "AddressLine2"         varchar(60),
 "AnnualSales"          number(38,0),
 "BankName"             varchar(50),
 "MinPaymentType"       number(38,0),
 "MinPaymentAmount"     number(38,0),
 "AnnualRevenue"        number(38,0),
 "YearOpened"           number(38,0),
 CONSTRAINT "PK_DimReseller_ResellerKey_PkDimReseller" PRIMARY KEY ( "ResellerKey" ),
 CONSTRAINT "FkDimReseller411" FOREIGN KEY ( "GeographyKey" ) REFERENCES "EDW"."DimGeography" ( "GeographyKey" )
);

-- ************************************** "EDW"."DimProductSubcategory"
CREATE OR REPLACE TABLE "EDW"."DimProductSubcategory"
(
 "ProductCategoryKey"            number(38,0) NOT NULL,
 "SpanishProductSubcategoryName" varchar(50) NOT NULL,
 "ProductSubcategoryKey"         number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'key of subcat',
 CONSTRAINT "PK_DimProductSubcategory__1894" PRIMARY KEY ( "ProductCategoryKey" ),
 CONSTRAINT "FkDimProductSubcategory409" FOREIGN KEY ( "ProductCategoryKey" ) REFERENCES "EDW"."DimProductCategory" ( "ProductCategoryKey" )
);

-- ************************************** "EDW"."DimEmployee"
CREATE OR REPLACE TABLE "EDW"."DimEmployee"
(
 "EmpKey"                               number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 "ParentEmployeeKey"                    number(38,0),
 "EmployeeNationalIDAlternateKey"       varchar(15),
 "ParentEmployeeNationalIDAlternateKey" varchar(15),
 "SalesTerritoryKey"                    number(38,0),
 "FirstName"                            varchar(50) NOT NULL,
 "LastName"                             varchar(50) NOT NULL,
 "MiddleName"                           varchar(50),
 "NameStyle"                            number(38,0) NOT NULL,
 "Title"                                varchar(50),
 "HireDate"                             date,
 "BirthDate"                            date,
 "LoginID"                              varchar(256),
 "EmailAddress"                         varchar(50),
 "Phone"                                varchar(25),
 "MaritalStatus"                        varchar(1),
 "EmergencyContactName"                 varchar(50),
 "EmergencyContactPhone"                varchar(25),
 "SalariedFlag"                         number(38,0),
 "Gender"                               varchar(1),
 "PayFrequency"                         number(38,0),
 "BaseRate"                             number(38,0),
 "VacationHours"                        number(38,0),
 "SickLeaveHours"                       number(38,0),
 "CurrentFlag"                          number(38,0) NOT NULL,
 "SalesPersonFlag"                      number(38,0) NOT NULL,
 "DepartmentName"                       varchar(50),
 "StartDate"                            date,
 "EndDate"                              date,
 "Status"                               varchar(50),
 CONSTRAINT "PK_DimEmployee" PRIMARY KEY ( "EmpKey" ),
 CONSTRAINT "FK_DimEmployee_403" FOREIGN KEY ( "ParentEmployeeKey" ) REFERENCES "EDW"."DimEmployee" ( "EmpKey" ),
 CONSTRAINT "FK_DimEmployee_405" FOREIGN KEY ( "SalesTerritoryKey" ) REFERENCES "EDW"."DimSalesTerritory" ( "SalesTerritoryKey" )
);

-- ************************************** "EDW"."DimCustomer"
CREATE OR REPLACE TABLE "EDW"."DimCustomer"
(
 "CustomerKey"          number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'Customer Identifier',
 "GeographyKey"         number(38,0) COMMENT 'Geographic informatio',
 "CustomerAlternateKey" varchar(15) NOT NULL COMMENT 'Alternate Key',
 "Title"                varchar(8) COMMENT 'Title of the Customer',
 "FirstName"            varchar(50),
 "MiddleName"           varchar(50),
 "LastName"             varchar(50),
 "NameStyle"            varchar(5) COMMENT 'First or last name',
 "BirthDate"            date,
 "MaritalStatus"        varchar(1),
 "Suffix"               varchar(10),
 "Gender"               varchar(1),
 "EmailAddress"         varchar(50),
 "YearlyIncome"         number(38,0),
 "TotalChildren"        number(38,0),
 "NumberChildrenAtHome" number(38,0) COMMENT 'hopefully none',
 "EnglishEducation"     varchar(40),
 "SpanishEducation"     varchar(40),
 "FrenchEducation"      varchar(40),
 "EnglishOccupation"    varchar(100),
 "SpanishOccupation"    varchar(100),
 "FrenchOccupation"     varchar(100),
 "HouseOwnerFlag"       varchar(1),
 "NumberCarsOwned"      number(38,0),
 "AddressLine"          varchar(120),
 "AddressLine2"         varchar(120),
 "Phone"                varchar(20),
 "DateFirstPurchase"    date,
 "CommuteDistance"      varchar(15),
 CONSTRAINT "PK_DimCustomer_CustomerKey_PkDimCustomer" PRIMARY KEY ( "CustomerKey" ),
 CONSTRAINT "FkDimCustomer401" FOREIGN KEY ( "GeographyKey" ) REFERENCES "EDW"."DimGeography" ( "GeographyKey" )
)
COMMENT = 'Dimension for Customer Data';

-- ************************************** "EDW"."ChildDemo"
CREATE OR REPLACE TABLE "EDW"."ChildDemo"
(
 "ScenarioKey" number(38,0) NOT NULL COMMENT 'Scenario Identifier',
 "CreatedBy"   varchar(50) NOT NULL,
 "CreatedDate" timestamp_ntz(9) NOT NULL,
 "UpdatedDate" timestamp_ntz(9) NOT NULL,
 "UpdatedBy"   varchar(50) NOT NULL,
 CONSTRAINT "PK_ChildDemo_ScenarioKey_Pk664" PRIMARY KEY ( "ScenarioKey" ),
 CONSTRAINT "Fk661" FOREIGN KEY ( "ScenarioKey" ) REFERENCES "EDW"."DimScenario" ( "ScenarioKey" )
);

-- ************************************** "Table544Copy11Copy1"
CREATE OR REPLACE TABLE "Table544Copy11Copy1"
(
 "NewCol"                integer NOT NULL,
 "SalesOrderNumber"      varchar(20) NOT NULL,
 "UnitPrice"             number(38,0) NOT NULL,
 "UnitPrice1"            number(38,0) NOT NULL,
 "ExtendedAmount1"       number(38,0) NOT NULL,
 "UnitPriceDiscountPct1" float,
 "ExtendedAmount"        number(38,0) NOT NULL,
 "UnitPriceDiscountPct"  float,
 "NewCol123"             date NOT NULL,
 CONSTRAINT "Fk545Copy11Copy1" FOREIGN KEY ( "NewCol" ) REFERENCES "EDW"."FactInternetSalesCopy11Copy1" ( "NewCol" )
);

-- ************************************** "Table1828"
CREATE OR REPLACE TABLE "Table1828"
(
 "ProductCategoryKey"             number(38,0) NOT NULL,
 "EtlId"                          date NOT NULL COMMENT 'hello', -- From template: "table_w_etl_fields" 
 "EtlFilename"                    varchar(50) NOT NULL COMMENT 'source file or table from where the target is loaded', -- From template: "table_w_etl_fields" 
 "ProductSubcategoryAlternateKey" number(38,0),
 "EnglishProductSubcategoryName"  varchar(50) NOT NULL,
 "FrenchProductSubcategoryName"   varchar(50) NOT NULL,
 CONSTRAINT "PK_Table1828__1897" PRIMARY KEY ( "ProductCategoryKey" ),
 CONSTRAINT "Fk1831" FOREIGN KEY ( "ProductCategoryKey" ) REFERENCES "EDW"."DimProductSubcategory" ( "ProductCategoryKey" )
);

-- ************************************** "EDW"."DimProduct"
CREATE OR REPLACE TABLE "EDW"."DimProduct"
(
 "ProductKey"            number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'from our main CRM tool',
 "ProductAlternateKey"   varchar(25),
 "WeightUnitMeasureCode" varchar(3),
 "SizeUnitMeasureCode"   varchar(3),
 "EnglishProductName"    varchar(50) NOT NULL,
 "SpanishProductName"    varchar(50),
 "FrenchProductName"     varchar(50),
 "StandardCost"          number(38,0),
 "FinishedGoodsFlag"     number(38,0) NOT NULL,
 "Color"                 varchar(15) NOT NULL,
 "SafetyStockLevel"      number(38,0),
 "ReorderPoint"          number(38,0),
 "ListPrice"             number(38,0) COMMENT 'prince on website',
 "Size"                  varchar(50),
 "SizeRange"             varchar(50),
 "Weight"                float,
 "DaysToManufacture"     number(38,0),
 "ProductLine"           varchar(2),
 "DealerPrice"           number(38,0) COMMENT 'customer price',
 "Class"                 varchar(2),
 "Style"                 varchar(2),
 "ModelName"             varchar(50),
 "EnglishDescription"    varchar(400),
 "FrenchDescription"     varchar(400),
 "ChineseDescription"    varchar(400),
 "ArabicDescription"     varchar(400),
 "HebrewDescription"     varchar(400),
 "ThaiDescription"       varchar(400),
 "GermanDescription"     varchar(400),
 "JapaneseDescription"   varchar(400),
 "TurkishDescription"    varchar(400),
 "Status"                varchar(7),
 "NewCol"                varchar(50) NOT NULL,
 "ProductCategoryKey"    number(38,0) NOT NULL COMMENT 'from our crm tool',
 CONSTRAINT "PK_DimProduct_ProductKey_PkDimProduct" PRIMARY KEY ( "ProductKey" ),
 CONSTRAINT "FkDimProduct407" FOREIGN KEY ( "ProductCategoryKey" ) REFERENCES "EDW"."DimProductSubcategory" ( "ProductCategoryKey" )
);

-- ************************************** "EDW"."FactResellerSales"
CREATE OR REPLACE TABLE "EDW"."FactResellerSales"
(
 "SaleSkey"              varchar NOT NULL,
 "ProductKey"            number(38,0) NOT NULL,
 "OrderDateKey"          number(38,0) NOT NULL,
 "DueDateKey"            number(38,0) NOT NULL,
 "ShipDateKey"           number(38,0) NOT NULL,
 "ResellerKey"           number(38,0) NOT NULL,
 "EmpKey"                number(38,0) NOT NULL,
 "PromotionKey"          number(38,0) NOT NULL,
 "CurrencyKey"           number(38,0) NOT NULL,
 "SalesTerritoryKey"     number(38,0) NOT NULL,
 "SalesOrderNumber"      varchar(20) NOT NULL,
 "SalesOrderLineNumber"  number(38,0) NOT NULL,
 "RevisionNumber"        number(38,0),
 "OrderQuantity"         number(38,0),
 "UnitPrice"             number(38,0),
 "ExtendedAmount"        number(38,0),
 "UnitPriceDiscountPct"  float,
 "DiscountAmount"        float,
 "ProductStandardCost"   number(38,0),
 "TotalProductCost"      number(38,0),
 "SalesAmount"           number(38,0),
 "TaxAmt"                number(38,0),
 "Freight"               number(38,0),
 "CarrierTrackingNumber" varchar(25),
 "CustomerPoNumber"      varchar(25),
 "SalesTerritoryGroup"   varchar(50) NOT NULL,
 CONSTRAINT "PK_FactResellerSales_SaleSkey_Pk917" PRIMARY KEY ( "SaleSkey" ),
 CONSTRAINT "FkFactResellerSales445" FOREIGN KEY ( "ProductKey" ) REFERENCES "EDW"."DimProduct" ( "ProductKey" ),
 CONSTRAINT "FkFactResellerSales447" FOREIGN KEY ( "ResellerKey" ) REFERENCES "EDW"."DimReseller" ( "ResellerKey" ),
 CONSTRAINT "FkFactResellerSales449" FOREIGN KEY ( "EmpKey" ) REFERENCES "EDW"."DimEmployee" ( "EmpKey" ),
 CONSTRAINT "FkFactResellerSales451" FOREIGN KEY ( "PromotionKey" ) REFERENCES "EDW"."DimPromotion" ( "PromotionKey" ),
 CONSTRAINT "FkFactResellerSales453" FOREIGN KEY ( "CurrencyKey" ) REFERENCES "EDW"."DimcUrrency" ( "CurrencyKey" ),
 CONSTRAINT "FkFactResellerSales455" FOREIGN KEY ( "SalesTerritoryKey", "SalesTerritoryGroup" ) REFERENCES "EDW"."DimSalesTerritory" ( "SalesTerritoryKey", "SalesTerritoryGroup" ),
 CONSTRAINT "FkFactResellerSales457" FOREIGN KEY ( "OrderDateKey" ) REFERENCES "EDW"."DimDate" ( "DateKey" ),
 CONSTRAINT "FkFactResellerSales459" FOREIGN KEY ( "DueDateKey" ) REFERENCES "EDW"."DimDate" ( "DateKey" ),
 CONSTRAINT "FkFactResellerSales461" FOREIGN KEY ( "ShipDateKey" ) REFERENCES "EDW"."DimDate" ( "DateKey" )
)
COMMENT = 'Fact data of Reseller Sales';

-- ************************************** "EDW"."FactInternetSales"
CREATE OR REPLACE TRANSIENT TABLE "EDW"."FactInternetSales"
(
 "NewCol"                integer NOT NULL,
 "ProductKey"            number(38,0) NOT NULL,
 "OrderDateKey"          number(38,0) NOT NULL,
 "DueDateKey"            number(38,0) NOT NULL,
 "ShipDateKey"           number(38,0) NOT NULL,
 "CustomerKey"           number(38,0) NOT NULL,
 "PromotionKey"          number(38,0) NOT NULL,
 "CurrencyKey"           number(38,0) NOT NULL,
 "SalesTerritoryKey"     number(38,0) NOT NULL,
 "SalesOrderNumber"      varchar(20) NOT NULL,
 "SalesOrderLineNumber"  number(38,0) NOT NULL,
 "RevisionNumberasdf"    number(38,0) NOT NULL,
 "OrderQuantity"         number(38,0) NOT NULL,
 "UnitPrice"             number(38,0) NOT NULL,
 "ExtendedAmount"        number(38,0) NOT NULL,
 "UnitPriceDiscountPct"  float,
 "DiscountAmount"        float NOT NULL,
 "ProductStandardCost"   number(38,0) NOT NULL,
 "TotalProductCost"      number(38,0) NOT NULL,
 "SalesAmount"           number(38,0) NOT NULL,
 "TaxAmt"                number(38,0) NOT NULL,
 "Freight"               number(38,0) NOT NULL,
 "CarrierTrackingNumber" varchar(25),
 "CustomerPoNumber"      varchar(25),
 "NewPk"                 varchar NOT NULL,
 "NewPk"                 integer NOT NULL,
 "NewPk1"                varchar NOT NULL,
 "NewCol1"               bigint NOT NULL,
 "Col1747"               bigint NOT NULL,
 "SalesTerritoryGroup"   varchar(50) NOT NULL,
 CONSTRAINT "PK_FactInternetSales_NewCol_Pk543" PRIMARY KEY ( "NewCol" ),
 CONSTRAINT "Fk549" FOREIGN KEY ( "NewPk" ) REFERENCES "Table548" ( "NewPk" ),
 CONSTRAINT "FkFactInternetSales427" FOREIGN KEY ( "ProductKey" ) REFERENCES "EDW"."DimProduct" ( "ProductKey" ),
 CONSTRAINT "FkFactInternetSales429" FOREIGN KEY ( "CustomerKey" ) REFERENCES "EDW"."DimCustomer" ( "CustomerKey" ),
 CONSTRAINT "FkFactInternetSales431" FOREIGN KEY ( "PromotionKey" ) REFERENCES "EDW"."DimPromotion" ( "PromotionKey" ),
 CONSTRAINT "FkFactInternetSales433" FOREIGN KEY ( "CurrencyKey" ) REFERENCES "EDW"."DimcUrrency" ( "CurrencyKey" ),
 CONSTRAINT "FkFactInternetSales435" FOREIGN KEY ( "SalesTerritoryKey", "SalesTerritoryGroup" ) REFERENCES "EDW"."DimSalesTerritory" ( "SalesTerritoryKey", "SalesTerritoryGroup" ),
 CONSTRAINT "FkFactInternetSales437" FOREIGN KEY ( "OrderDateKey" ) REFERENCES "EDW"."DimDate" ( "DateKey" ),
 CONSTRAINT "FkFactInternetSales439" FOREIGN KEY ( "DueDateKey" ) REFERENCES "EDW"."DimDate" ( "DateKey" ),
 CONSTRAINT "FkFactInternetSales441" FOREIGN KEY ( "ShipDateKey" ) REFERENCES "EDW"."DimDate" ( "DateKey" )
)
COMMENT = 'Fact table to hold Currency Data';

-- ************************************** "EDW"."ResellerSalesAnalysis"
CREATE OR REPLACE TABLE "EDW"."ResellerSalesAnalysis"
(
 "SaleSkey"              varchar NOT NULL,
 "StoreSizeCategory"     varchar(1) NOT NULL,
 "EmployeeTitle"         varchar(50) NOT NULL,
 "SalesOrderNumber"      varchar(20) NOT NULL,
 "CarrierTrackingNumber" varchar(25),
 "SalesOrderLineNumber"  number(38,0) NOT NULL,
 "RevisionNumber"        number(38,0),
 "OrderQuantity"         number(38,0),
 "UnitPrice"             number(38,0),
 "ExtendedAmount"        number(38,0),
 "UnitPriceDiscountPct"  float,
 "DiscountAmount"        float,
 "ProductStandardCost"   number(38,0),
 "TotalProductCost"      number(38,0),
 "SalesAmount"           number(38,0),
 "CustomerPoNumber"      varchar(25),
 CONSTRAINT "PK_ResellerSalesAnalysis_SaleSkey_Pk921" PRIMARY KEY ( "SaleSkey" ),
 CONSTRAINT "Fk918" FOREIGN KEY ( "SaleSkey" ) REFERENCES "EDW"."FactResellerSales" ( "SaleSkey" )
)
COMMENT = 'Fact data of Reseller Sales';

-- ************************************** "ResellerSalesAnalysis_v"
CREATE OR REPLACE VIEW "ResellerSalesAnalysis_v" as (
with emp_store as (
select * from DimEmployee
    inner join DimStore on 
    DimEmployee.StoreId = DimStore.StoreId
)
, Sales_dtl as (
select * from FactResellerSales 
inner join emp_store on
FactResellerSales.EmployeeKey = emp_store.EmployeeKey
)
, final as (
select 
SaleSkey,
SizeCategory as StoreSizeCategory,
Title as EmployeeTitle,
SalesOrderNumber,
CarrierTrackingNumber,
SalesOrderLineNumber,
RevisionNumber,
OrderQuantity,
UnitPrice,
ExtendedAmount,
UnitPriceDiscountPct,
DiscountAmount,
ProductStandardCost,
TotalProductCost,
SalesAmount,
CustomerPoNumber
from Sales_dtl
)
select * from final
);

-- ************************************** "ResellerSalesAnalysis_load"
CREATE OR REPLACE VIEW "ResellerSalesAnalysis_load"

  Comment = 'No Comment Provided'

AS
(
  
  /*
  * yaml source

version: 2
#customer sources# 
sources:

  - name: edw
    database: prod_hbg
    schema: source
    loaded_at_field: etl_timestamp
    freshness:
      warn_after: {count: 2, period: day}
      error_after: {count: 4, period: day}

    tables:

      - name: DimStore   
      - name: DimEmployee
      - name: FactResellerSales
         
        
  
  */
  
  
  
  /*
  *code
  
  with sales as (
    select * from {{ source('edw', 'FactResellerSales') }}
)

, emp as ( 
    select * from {{ source('edw', 'DimEmployee') }}
)

, store as ( 
    select * from {{ source('edw', 'DimStore') }}
)

, emp_store as (

    select * from emp 
    inner join store using(store_id)
) 

, trading as (
select * from sales 
inner join emp_store using (EmployeeKey)
) 

, final as (

select 
SaleSkey,
SizeCategory as StoreSizeCategory,
Title as EmployeeTitle,
SalesOrderNumber,
CarrierTrackingNumber,
SalesOrderLineNumber,
RevisionNumber,
OrderQuantity,
UnitPrice,
ExtendedAmount,
UnitPriceDiscountPct,
DiscountAmount,
ProductStandardCost,
TotalProductCost,
SalesAmount,
CustomerPoNumber 

from trading
)
  
  */
  select 1

);

-- ************************************** "EDW"."DIM_PRODUCT_CAT_SUBCAT_V2"
CREATE OR REPLACE VIEW "EDW"."DIM_PRODUCT_CAT_SUBCAT_V2" 

  comment = 'Product details with cat and subcat english names. For fwd/rev engineering' 

AS
(
WITH cat_subcat as (
SELECT cat.* , sub."ProductSubcategoryKey" as "SubProductSubcategoryKey", sub."EnglishProductSubcategoryName"  FROM "DimProductCategory" cat
inner join  "DimProductSubcategory" sub
on  cat."ProductCategoryKey" = sub."ProductCategoryKey"
) 
  select prod.* ,
  ProductCategoryKey,         
ProductCategoryAlternateKey,
EnglishProductCategoryName ,
EnglishProductSubcategoryName
  from "Edw"."DimProduct" prod
  left join cat_subcat 
  on prod."ProductSubcategoryKey" = cat_subcat."SubProductSubcategoryKey"
);

-- ************************************** "EDW"."DIM_PRODUCT_CAT_SUBCAT_V"
CREATE OR REPLACE VIEW ADVENTUREWORKSDW."EDW"."DIM_PRODUCT_CAT_SUBCAT_V" 

  comment = 'Product details with cat and subcat english names. For fwd/rev engineering' 

AS
(
WITH cat_subcat as (
SELECT cat.* , sub."ProductSubcategoryKey" as "SubProductSubcategoryKey", sub."EnglishProductSubcategoryName"  FROM "DimProductCategory" cat
inner join  "DimProductSubcategory" sub
on  cat."ProductCategoryKey" = sub."ProductCategoryKey"
) 
  select 
 "ProductKey"           
, "ProductAlternateKey"  
, "ProductSubcategoryKey"
, "WeightUnitMeasureCode"
, "SizeUnitMeasureCode"  
, "EnglishProductName"   
, "StandardCost"         
, "FinishedGoodsFlag"    
, "Color"                
, "SafetyStockLevel"     
, "ReorderPoint"         
, "ListPrice"            
, "Size"                 
 ,"SizeRange"            
 ,"Weight"               
 ,"DaysToManufacture"    
 ,"ProductLine"          
 ,"DealerPrice"          
 ,"Class"                
 ,"Style"                
 ,"ModelName"            
 ,"EnglishDescription"   
 ,"Status"                   
,"ProductCategoryKey"         
,"ProductCategoryAlternateKey"
,"EnglishProductCategoryName" 
,"EnglishProductSubcategoryName"
 from "DimProduct" prod
  left join cat_subcat 
  on prod."ProductSubcategoryKey" = cat_subcat."SubProductSubcategoryKey"
);

-- ************************************** "View745"
CREATE OR REPLACE VIEW "View745"

  Comment = 'No Comment Provided'

AS
(
  select * from "Edw"."DIM_PRODUCT_CAT_SUBCAT_V2"
);

