-- **************************** SqlDBM: Snowflake ***************************
-- * Generated by SqlDBM: AdWorks project, v459 vs v458 by serge@sqldbm.com *

ALTER TABLE IF EXISTS Racer
    DROP CONSTRAINT Fk2861;

ALTER TABLE IF EXISTS Racer
    DROP CONSTRAINT Fk2861;

ALTER TABLE IF EXISTS Car
    DROP CONSTRAINT Fk2930;

ALTER TABLE IF EXISTS Racer
    DROP CONSTRAINT Fk2962;

ALTER TABLE IF EXISTS Racer
    DROP CONSTRAINT Fk2962;

ALTER TABLE IF EXISTS Car
    DROP CONSTRAINT Fk2991;

ALTER TABLE IF EXISTS Person
    DROP CONSTRAINT Fk3005;

ALTER TABLE IF EXISTS DriversLicense
    DROP CONSTRAINT Fk3002;

ALTER TABLE IF EXISTS Racer
    DROP CONSTRAINT Fk3234;

ALTER TABLE IF EXISTS Racer
    DROP CONSTRAINT Fk3234;

ALTER TABLE IF EXISTS DriversLicense
    DROP CONSTRAINT Fk3231;

ALTER TABLE IF EXISTS Item
    DROP CONSTRAINT Fk3125;

ALTER TABLE IF EXISTS Item
    DROP CONSTRAINT Fk3129;

ALTER TABLE IF EXISTS InPersonCourse
    DROP CONSTRAINT Fk3170;

ALTER TABLE IF EXISTS OnlineCourse
    DROP CONSTRAINT Fk3173;

ALTER TABLE IF EXISTS Racer
    DROP CONSTRAINT PK_Racer_player_id_2831;

ALTER TABLE IF EXISTS Racer
    DROP CONSTRAINT PK_Racer_player_id_race_car_id_2831;

ALTER TABLE IF EXISTS Racer
    DROP CONSTRAINT PK_Racer_player_id_race_car_id_2831;

ALTER TABLE IF EXISTS Racer
    DROP CONSTRAINT PK_Racer_player_id_2831;

ALTER TABLE IF EXISTS Item
    DROP CONSTRAINT PK_Item__3126;

ALTER TABLE IF EXISTS "physical item"
    DROP CONSTRAINT PK_Item_item_id_3088;

ALTER TABLE IF EXISTS virtual_item
    DROP CONSTRAINT PK_Item_item_id_3088;

ALTER TABLE IF EXISTS Item
    DROP CONSTRAINT PK_Item_item_id_3126;

ALTER TABLE IF EXISTS "physical item"
    DROP CONSTRAINT PK_Item_item_id_3088;

ALTER TABLE IF EXISTS virtual_item
    DROP CONSTRAINT PK_Item_item_id_3088;

-- Attention! Cannot change column data type.

ALTER TABLE IF EXISTS Edw.FactInternetSales
    ALTER COLUMN NewPk SET DATA TYPE integer;

-- Attention! Cannot change column data type.

ALTER TABLE IF EXISTS Edw.FactInternetSales
    ALTER COLUMN NewPk SET DATA TYPE varchar;

ALTER TABLE IF EXISTS DimEmployee
    ADD COLUMN new_col varchar(50) NOT NULL;

ALTER TABLE IF EXISTS Racer
    DROP COLUMN team_id;

ALTER TABLE IF EXISTS Racer
    ADD COLUMN race_car_id  NOT NULL;

ALTER TABLE IF EXISTS Racer
    DROP COLUMN team_id;

ALTER TABLE IF EXISTS Racer
    ADD COLUMN license_id  NOT NULL;

ALTER TABLE IF EXISTS Person
    ADD COLUMN license_id ;

ALTER TABLE IF EXISTS Car
    DROP COLUMN person_id;

ALTER TABLE IF EXISTS Car
    ADD COLUMN spot_id ;

ALTER TABLE IF EXISTS Racer
    DROP COLUMN race_car_id;

ALTER TABLE IF EXISTS Racer
    ADD COLUMN team_id  NOT NULL;

ALTER TABLE IF EXISTS Racer
    DROP COLUMN race_car_id;

ALTER TABLE IF EXISTS Racer
    ADD COLUMN license_id  NOT NULL;

ALTER TABLE IF EXISTS Car
    DROP COLUMN spot_id;

ALTER TABLE IF EXISTS Car
    ADD COLUMN person_id ;

ALTER TABLE IF EXISTS Person
    DROP COLUMN license_id;

ALTER TABLE IF EXISTS DriversLicense
    DROP COLUMN person_id;

ALTER TABLE IF EXISTS DriversLicense
    ADD COLUMN player_id  NOT NULL;

ALTER TABLE IF EXISTS Racer
    DROP COLUMN license_id;

ALTER TABLE IF EXISTS Racer
    ADD COLUMN team_id  NOT NULL;

ALTER TABLE IF EXISTS Racer
    DROP COLUMN license_id;

ALTER TABLE IF EXISTS Racer
    ADD COLUMN race_car_id  NOT NULL;

ALTER TABLE IF EXISTS DriversLicense
    DROP COLUMN player_id;

ALTER TABLE IF EXISTS DriversLicense
    ADD COLUMN person_id  NOT NULL;

ALTER TABLE IF EXISTS Item
    ADD COLUMN item_type  NOT NULL;

ALTER TABLE IF EXISTS Item
    ADD COLUMN weight  NOT NULL;

ALTER TABLE IF EXISTS Item
    ADD COLUMN url  NOT NULL;

-- Attention! Table "physical item" - column item_id: default constraint cannot be changed. Snowflake doesn't support this syntax.

ALTER TABLE IF EXISTS "physical item"
    ALTER COLUMN item_id SET DATA TYPE integer;

ALTER TABLE IF EXISTS "physical item"
    ADD COLUMN vi  NOT NULL;

-- Attention! Table virtual_item - column item_id: default constraint cannot be changed. Snowflake doesn't support this syntax.

ALTER TABLE IF EXISTS virtual_item
    ALTER COLUMN item_id SET DATA TYPE integer;

ALTER TABLE IF EXISTS virtual_item
    ADD COLUMN virtual_item_id  NOT NULL;

ALTER TABLE IF EXISTS Item
    DROP COLUMN item_type;

ALTER TABLE IF EXISTS Item
    DROP COLUMN weight;

ALTER TABLE IF EXISTS Item
    DROP COLUMN url;

ALTER TABLE IF EXISTS "physical item"
    ALTER COLUMN item_id DROP DEFAULT;

-- Attention! Cannot change column data type.

ALTER TABLE IF EXISTS "physical item"
    ALTER COLUMN item_id SET DATA TYPE ;

ALTER TABLE IF EXISTS "physical item"
    DROP COLUMN vi;

ALTER TABLE IF EXISTS virtual_item
    ALTER COLUMN item_id DROP DEFAULT;

-- Attention! Cannot change column data type.

ALTER TABLE IF EXISTS virtual_item
    ALTER COLUMN item_id SET DATA TYPE ;

ALTER TABLE IF EXISTS virtual_item
    DROP COLUMN virtual_item_id;

ALTER TABLE IF EXISTS CollegeCourse
    ADD COLUMN "room number" ;

ALTER TABLE IF EXISTS CollegeCourse
    ADD COLUMN url ;

ALTER TABLE IF EXISTS CollegeCourse
    ADD COLUMN is_in_person_course boolean NOT NULL;

ALTER TABLE IF EXISTS CollegeCourse
    ADD COLUMN is_ionline_course boolean NOT NULL;

ALTER TABLE IF EXISTS InPersonCourse
    DROP COLUMN course_id;

ALTER TABLE IF EXISTS OnlineCourse
    DROP COLUMN course_id;

ALTER TABLE IF EXISTS CollegeCourse
    DROP COLUMN "room number";

ALTER TABLE IF EXISTS CollegeCourse
    DROP COLUMN url;

ALTER TABLE IF EXISTS CollegeCourse
    DROP COLUMN is_in_person_course;

ALTER TABLE IF EXISTS CollegeCourse
    DROP COLUMN is_ionline_course;

ALTER TABLE IF EXISTS InPersonCourse
    ADD COLUMN course_id  NOT NULL;

ALTER TABLE IF EXISTS OnlineCourse
    ADD COLUMN course_id  NOT NULL;

ALTER TABLE IF EXISTS Racer
    ADD CONSTRAINT PK_Racer_player_id_race_car_id_2831 PRIMARY KEY (player_id, race_car_id);

ALTER TABLE IF EXISTS Racer
    ADD CONSTRAINT PK_Racer_player_id_2831 PRIMARY KEY (player_id);

ALTER TABLE IF EXISTS Racer
    ADD CONSTRAINT PK_Racer_player_id_2831 PRIMARY KEY (player_id);

ALTER TABLE IF EXISTS Racer
    ADD CONSTRAINT PK_Racer_player_id_race_car_id_2831 PRIMARY KEY (player_id, race_car_id);

ALTER TABLE IF EXISTS Item
    ADD CONSTRAINT PK_Item_item_id_3126 PRIMARY KEY (item_id);

ALTER TABLE IF EXISTS "physical item"
    ADD CONSTRAINT PK_Item_item_id_3088 PRIMARY KEY (item_id);

ALTER TABLE IF EXISTS virtual_item
    ADD CONSTRAINT PK_Item_item_id_3088 PRIMARY KEY (item_id);

ALTER TABLE IF EXISTS Item
    ADD CONSTRAINT PK_Item__3126 PRIMARY KEY (item_id);

ALTER TABLE IF EXISTS "physical item"
    ADD CONSTRAINT PK_Item_item_id_3088 PRIMARY KEY (item_id);

ALTER TABLE IF EXISTS virtual_item
    ADD CONSTRAINT PK_Item_item_id_3088 PRIMARY KEY (item_id);

CREATE TABLE IF NOT EXISTS dim_emp2
(
 EtlId       date NOT NULL COMMENT 'hello desc', 
 EtlFilename varchar(50) NOT NULL COMMENT 'source file or table from where the target is loaded' 
);

ALTER TABLE IF EXISTS Racer
    ADD CONSTRAINT Fk2962 FOREIGN KEY (race_car_id) REFERENCES RaceCar (race_car_id);

ALTER TABLE IF EXISTS Racer
    ADD CONSTRAINT Fk3234 FOREIGN KEY (license_id) REFERENCES DriversLicense (license_id);

ALTER TABLE IF EXISTS Person
    ADD CONSTRAINT Fk3005 FOREIGN KEY (license_id) REFERENCES DriversLicense (license_id);

ALTER TABLE IF EXISTS Car
    ADD CONSTRAINT Fk2991 FOREIGN KEY (spot_id) REFERENCES PublicParking (spot_id);

ALTER TABLE IF EXISTS Racer
    ADD CONSTRAINT Fk2861 FOREIGN KEY (team_id) REFERENCES Team (team_id);

ALTER TABLE IF EXISTS Racer
    ADD CONSTRAINT Fk3234 FOREIGN KEY (license_id) REFERENCES DriversLicense (license_id);

ALTER TABLE IF EXISTS Car
    ADD CONSTRAINT Fk2930 FOREIGN KEY (person_id) REFERENCES Person (person_id);

ALTER TABLE IF EXISTS DriversLicense
    ADD CONSTRAINT Fk3231 FOREIGN KEY (player_id) REFERENCES Racer (player_id);

ALTER TABLE IF EXISTS Racer
    ADD CONSTRAINT Fk2861 FOREIGN KEY (team_id) REFERENCES Team (team_id);

ALTER TABLE IF EXISTS Racer
    ADD CONSTRAINT Fk2962 FOREIGN KEY (race_car_id) REFERENCES RaceCar (race_car_id);

ALTER TABLE IF EXISTS DriversLicense
    ADD CONSTRAINT Fk3002 FOREIGN KEY (person_id) REFERENCES Person (person_id);

ALTER TABLE IF EXISTS Item
    ADD CONSTRAINT Fk3125 FOREIGN KEY (item_id) REFERENCES "physical item" (item_id);

ALTER TABLE IF EXISTS Item
    ADD CONSTRAINT Fk3129 FOREIGN KEY (item_id) REFERENCES virtual_item (item_id);

ALTER TABLE IF EXISTS InPersonCourse
    ADD CONSTRAINT Fk3170 FOREIGN KEY (course_id) REFERENCES CollegeCourse (course_id);

ALTER TABLE IF EXISTS OnlineCourse
    ADD CONSTRAINT Fk3173 FOREIGN KEY (course_id) REFERENCES CollegeCourse (course_id);