-- **************************** SqlDBM: Snowflake ***************************
-- * Generated by SqlDBM: AdWorks project, v773 vs v771 by serge@sqldbm.com *

ALTER TABLE IF EXISTS Table2514
    ADD COLUMN EtlId_1 date NOT NULL;

ALTER TABLE IF EXISTS Table2514
    ADD COLUMN EtlFilename_1 varchar(50) NOT NULL;

CREATE TABLE IF NOT EXISTS Table123_1
(
 EtlId_1       date NOT NULL,
 EtlFilename_1 varchar(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS Table2514_copy_1
(
 EtlId       date NOT NULL COMMENT 'hello desc', 
 EtlFilename varchar(50) NOT NULL COMMENT 'source file or table from where the target is loaded', 
 Col5        varchar NOT NULL
);