-- ************************** SqlDBM: Snowflake *************************
-- *** Generated by SqlDBM: AdWorks project, v459 by serge@sqldbm.com ***


-- ************************************** dim_emp2
CREATE OR REPLACE TABLE dim_emp2
(
 EtlId       date NOT NULL COMMENT 'hello desc', -- From template: "table_w_etl_fields" 
 EtlFilename varchar(50) NOT NULL COMMENT 'source file or table from where the target is loaded' -- From template: "table_w_etl_fields"
);
