-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


-- ************************************** DimAccount
CREATE OR REPLACE TABLE DimAccount
(
 AccountKey                    number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'Unique Identifier of the Account data from Salesforce',
 ParentPk                      varchar NOT NULL,
 ParentAccountKey              number(38,0) NOT NULL COMMENT 'Identifier of parent Account',
 AccountCodeAlternateKey       number(38,0) COMMENT 'from legacy system',
 ParentAccountCodeAlternateKey number(38,0),
 AccountDescription            varchar(500) COMMENT 'new comment',
 AccountType                   boolean COMMENT 'type 1 2 or 3',
 Operator                      varchar(500) COMMENT 'whatever an operator is',
 CustomMembers                 varchar(300),
 ValueType                     varchar(50) COMMENT 'defined by Bob',
 Amount                        float NOT NULL,
 CustomMemberOptions           varchar(200),
 NewCol                        integer NOT NULL,
 CONSTRAINT PK_DimAccount_AccountKey_ParentPk_PkDimAccount PRIMARY KEY ( AccountKey, ParentPk ),
 CONSTRAINT Fk3351 FOREIGN KEY ( ParentPk ) REFERENCES Table3348 ( ParentPk )
)
COMMENT = 'Holds all Account information';
