-- ************************** SqlDBM: Snowflake *************************
-- *** Generated by SqlDBM: AdWorks project, v459 by serge@sqldbm.com ***


-- ************************************** DimEmployee
CREATE OR REPLACE TABLE DimEmployee
(
 EmployeeId  integer NOT NULL DEFAULT 5,
 EtlId       date NOT NULL COMMENT 'hello desc', -- From template: "table_w_etl_fields" 
 EtlFilename varchar(50) NOT NULL COMMENT 'source file or table from where the target is loaded', -- From template: "table_w_etl_fields" 
 new_col     varchar(50) NOT NULL,
 CONSTRAINT PK_DimEmployee_EmployeeId_1600 PRIMARY KEY ( EmployeeId )
);
