-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


-- ************************************** DimProdCat
CREATE OR REPLACE TABLE DimProdCat
(
 CategoryId      integer NOT NULL,
 EtlId           date NOT NULL COMMENT 'hello desc', -- From template: "table_w_etl_fields" 
 OrganizationKey number(38,0) NOT NULL,
 CalendarYear    number(38,0) NOT NULL,
 AccountKey      number(38,0) NOT NULL,
 EtlFilename     varchar(50) NOT NULL COMMENT 'source file or table from where the target is loaded', -- From template: "table_w_etl_fields" 
 CONSTRAINT PK_DimProdCat_CategoryId_3308 PRIMARY KEY ( CategoryId )
);
