-- ************************** SqlDBM: Snowflake *************************
-- *** Generated by SqlDBM: AdWorks project, v458 by serge@sqldbm.com ***


-- ************************************** Edw.DimEmployee
CREATE OR REPLACE TABLE Edw.DimEmployee
(
 EmpKey                               number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 ParentEmployeeKey                    number(38,0),
 EmployeeNationalIdAlternateKey       varchar(15),
 ParentEmployeeNationalIdAlternateKey varchar(15),
 SalesTerritoryKey                    number(38,0),
 FirstName                            varchar(50) NOT NULL,
 LastName                             varchar(50) NOT NULL,
 MiddleName                           varchar(50),
 NameStyle                            number(38,0) NOT NULL,
 Title                                varchar(50),
 HireDate                             date,
 BirthDate                            date,
 LoginId                              varchar(256),
 Emailaddress                         varchar(50),
 Phone                                varchar(25),
 MaritalStatus                        varchar(1),
 EmergencyContactName                 varchar(50),
 EmergencyContactPhone                varchar(25),
 SalariedFlag                         number(38,0),
 Gender                               varchar(1),
 PayFrequency                         number(38,0),
 BaseRate                             number(38,0),
 VacationHours                        number(38,0),
 SickLeaveHours                       number(38,0),
 CurrentFlag                          number(38,0) NOT NULL,
 SalesPersonFlag                      number(38,0) NOT NULL,
 DepartmentName                       varchar(50),
 StartDate                            date,
 EndDate                              date,
 Status                               varchar(50),
 CONSTRAINT PK_DimEmployee_EmpKey_PkDimEmployee PRIMARY KEY ( EmpKey ),
 CONSTRAINT FkDimEmployee403 FOREIGN KEY ( ParentEmployeeKey ) REFERENCES Edw.DimEmployee ( EmpKey ),
 CONSTRAINT FkDimEmployee405 FOREIGN KEY ( SalesTerritoryKey ) REFERENCES Edw.DimSalesTerritory ( SalesTerritoryKey )
);
