-- ************************** SqlDBM: Snowflake *************************
-- *** Generated by SqlDBM: AdWorks project, v458 by serge@sqldbm.com ***


-- ************************************** Edw.DimCustomer
CREATE OR REPLACE TABLE Edw.DimCustomer
(
 CustomerKey          number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'Customer Identifier loaded from salesforce',
 GeographyKey         number(38,0) COMMENT 'Geographic informatio',
 CustomerAlternateKey varchar(15) NOT NULL COMMENT 'Alternate Key',
 Title                varchar(8) COMMENT 'Title of the Customer',
 FirstName            varchar(50) COMMENT 'cust first name',
 MiddleName           varchar(50),
 LastName             varchar(50),
 NameStyle            varchar(5) COMMENT 'First or last name',
 BirthDate            date COMMENT 'remember to flag as PII',
 MaritalStatus        varchar(1),
 Suffix               varchar(10),
 Gender               varchar(1),
 Emailaddress         varchar(50),
 YearlyIncome         number(38,0),
 TotalChildren        number(38,0),
 NumberChildrenAtHome number(38,0) COMMENT 'hopefully none',
 EnglishEducation     varchar(40),
 SpanishEducation     varchar(40),
 FrenchEducation      varchar(40),
 EnglishOccupation    varchar(100),
 SpanishOccupation    varchar(100),
 FrenchOccupation     varchar(100),
 HouseOwnerFlag       varchar(1),
 NumberCarsOwned      number(38,0),
 AddressLine          varchar(120),
 AddressLine2         varchar(120),
 Phone                varchar(20) COMMENT 'area code and phone',
 DateFirstPurchase    date COMMENT 'when first purchased and not returned',
 CommuteDistance      varchar(15),
 CONSTRAINT PK_DimCustomer_CustomerKey_PkDimCustomer PRIMARY KEY ( CustomerKey ),
 CONSTRAINT FkDimCustomer401 FOREIGN KEY ( GeographyKey ) REFERENCES Edw.DimGeography ( GeographyKey )
)
COMMENT = 'Dimension for Customer Data';
